### ISSUE TITLE
Add .aurp file documentation

### ISSUE THREAD

**Issue by tkulpa** [Smertig/among-us-replay-mod#11]
Add documentation for .aurp files, so people can write additional tooling for replays already created with your mod

I want to create small web tool to watch replays online

Kinda duplicate of https://github.com/Smertig/among-us-replay-mod/issues/2

**Comment by Smertig** [comment]
Done: [wiki](https://github.com/Smertig/among-us-replay-mod/wiki/1.-Dev:-aurp-format-specification)
Feel free to reopen issue if you have any questions.

**Comment by tkulpa** [comment]
@Smertig
Thanks for documentation, I made [NodeJS file parser with drawing example](https://github.com/tkulpa/among-us-replay-nodejs)
