### ISSUE TITLE
Does not work with "Among Us" downloaded from Epic games

### ISSUE THREAD

**Issue by yasyakami** [Smertig/among-us-replay-mod#12]
Hello, I'm very interested in this Replay mod. I think this Replay mod is very cool and I want to use it. However, I'm sad to say that it doesn't work on "Among Us", which I downloaded from Epic Games instead of STEAM.

If there is anything I need to check, or if there are any logs I need, I will provide them to you, and I hope you will consider making a Replay mod that works on Epic Games.

Thank you in advance.

**Comment by Smertig** [comment]
Fixed in [v0.8.1](https://github.com/Smertig/among-us-replay-mod/releases/tag/v0.8.1)
