### ISSUE TITLE
New Version Support

### ISSUE THREAD

**Issue by nobu02** [Smertig/among-us-replay-mod#13]
Will the new version be supported?
I think many users are looking forward to it.
I look forward to dealing with it.

**Comment by Smertig** [comment]
Checkout [v0.7.0](https://github.com/Smertig/among-us-replay-mod/releases/tag/v0.7.0) for **v2021.3.5s** game version support

**Comment by nobu02** [comment]
Thank you for supporting the new version.
It's a very convenient tool, so I'm happy to be able to handle it.
I am also looking forward to the next 3/31 update.

**Comment by Smertig** [comment]
You are welcome!
I'm glad you are using this mod.

**Comment by r1bnc** [comment]
Bump,  new version again.

**Comment by nobu02** [comment]
@Smertig 
thank you for new version support.

**Comment by r1bnc** [comment]
Thanks @Smertig :D

**Comment by nobu02** [comment]
Bump, new version again.
