### ISSUE TITLE
new version support again.

### ISSUE THREAD

**Issue by nobu02** [Smertig/among-us-replay-mod#15]
Thank you for developing a wonderful program.

I know a little bit about development,
If you can easily adapt to the new version,
I will work if you tell me how to deal with the new version.

**Comment by Johannes7k75** [comment]
I have made a work and it is currently building a new Version but it only can inject itself.
If it wants to record it returns `[replay-mod] [info] InnerNet::InnerNetClient::Update: GameData::instance() is null` no idea about that

**Comment by Smertig** [comment]
I'll do my best. It's over a year since last mod update, many game structures and mechanics were changed a lot. 

P.S. Glad to see that somebody still uses this mod

**Comment by Johannes7k75** [comment]
The reason why i want to use it is that is has a the nicest gui, from the apps i seen and tested.

**Comment by Smertig** [comment]
Checkout [v0.8.0](https://github.com/Smertig/among-us-replay-mod/releases/tag/v0.7.0) for **v2022.3.29s** game version support
