### ISSUE TITLE
Add Epic Games version support

### ISSUE THREAD

**Issue by Johannes7k75** [Smertig/among-us-replay-mod#16]
it think it should be very simple 
Just edit the s at the end of the gamestring to e

**Comment by Smertig** [comment]
There is no `s` at the end of the [gamestring](https://github.com/Smertig/among-us-replay-mod/blob/31a1694c7570e471dd08d4e8cec86d73f5d717e6/source/utils/mod_info.cpp#L23), `UnityEngine::Application` returns `"2022.3.29"`. Could you please elaborate what's wrong with Epic Games game version?

**Comment by Johannes7k75** [comment]
Then why does it say the version is not supported?
![grafik](https://user-images.githubusercontent.com/57235955/174145720-926e4149-b038-4c0d-9bf2-8c486a8cba4d.png)
its the same version `2022.4.19`

**Comment by Johannes7k75** [comment]
my bad its version `2022.4.19` and not `2022.3.29`

**Comment by Smertig** [comment]
> my bad its version `2022.4.19` and not `2022.3.29`

Exactly. Could you manually build 0.8.0 version with changed `"2022.3.29"` -> `"2022.4.19"` string? If it works, I'll make an update. Unfortunately, I can test it myself, because I don't have Epic Games version.

**Comment by Johannes7k75** [comment]
Works but i cant load the Replay with the player.
There are players, bodies and ghosts missing

**Comment by Smertig** [comment]
As I said in 0.8.0 release notes, replayer should be updated too, I'm going to work on it. As a workaround you can add missing files by copy-pasting them.

**Comment by Johannes7k75** [comment]
Yes it works but i have used `v2022_4_19e` and not `v2022_4_19s`

**Comment by Johannes7k75** [comment]
nvm the `e` or `s` doesn't mater at all

**Comment by Smertig** [comment]
Fixed in [v0.8.1](https://github.com/Smertig/among-us-replay-mod/releases/tag/v0.8.1)
