### ISSUE TITLE
Crash on updating version to 2022.6.21

### ISSUE THREAD

**Issue by Johannes7k75** [Smertig/among-us-replay-mod#19]
I added the new vars in the `mod_info.cpp` and `mod_info.hpp`.
The game crashes with this error shown in game 
![grafik](https://user-images.githubusercontent.com/57235955/174885019-f8d58c3f-5050-4a78-afce-bc49b54861c3.png)
[log_2022_06_21-21_42_42.txt](https://github.com/Smertig/among-us-replay-mod/files/8952334/log_2022_06_21-21_42_42.txt)

And here the error log

**Comment by Smertig** [comment]
It doesn't work that way. After every game update one should manually check and update all changed game structures (and functions if needed) and add new version enum only AFTER that. 

Luckily, 2022.3.29 and 2022.4.19 versions were binary compatible; but it looks like 2022.6.21 requires additional changes. I'll take a look.

**Comment by Johannes7k75** [comment]
I thought is was so easy.

**Comment by Johannes7k75** [comment]
How would i do this. Check the binarys?

**Comment by Smertig** [comment]
I use `Il2CppDumper` to dump binaries and extract game structures. You can try it, but it may be difficult for the first time.

**Comment by Johannes7k75** [comment]
Do i need a other decompiled version of the game if i want to see what methods have changed.
And how would i get it the only way i know to get the game is the installed version from epic games.

**Comment by Smertig** [comment]
Please, attach generated `il2cpp.h` and `dump.cs` files here, I'll compare them with a previous version

**Comment by Johannes7k75** [comment]
[II2CppDumper.zip](https://github.com/Smertig/among-us-replay-mod/files/8985204/II2CppDumper.zip)

**Comment by Smertig** [comment]
> [II2CppDumper.zip](https://github.com/Smertig/among-us-replay-mod/files/8985204/II2CppDumper.zip)

Thanks. Steam version was updated to 2022.6.21 too, so in 31b38345dcc2becaaad8e57e5c5e91ec90a44745 I added support for both Epic and Stream game versions.
