### ISSUE TITLE
Update for 2022.7.12

### ISSUE THREAD

**Issue by Johannes7k75** [Smertig/among-us-replay-mod#21]
I tried it myself with the il2cpp marked types but they are all the same.

**Comment by Smertig** [comment]
Thanks for information. I'll slightly refactor versioning stuff in the next mod update, so you won't need to do anything if mod is still compatible with the new game version

**Comment by Smertig** [comment]
Fixed in **[v0.9.0](https://github.com/Smertig/among-us-replay-mod/releases/tag/v0.9.0)**
