### ISSUE TITLE
Add v2020.10.22 support

### ISSUE THREAD

**Issue by Smertig** [Smertig/among-us-replay-mod#3]

**Comment by r1bnc** [comment]
Prior to v2020.10.22 which versions does it support?

**Comment by Smertig** [comment]
For now the following game versions are supported: 
- v2020.6.9s
- v2020.9.22s
- v2020.10.8i (beta)

It's mentioned at releases page.

**Comment by r1bnc** [comment]
Among us has a new update, 12.3s if i remember correctly.

**Comment by Smertig** [comment]
@gr01d, thanks, I'll update mod soon

**Comment by r1bnc** [comment]
They've released another one it is 12.5s
