### ISSUE TITLE
Add a way to check if the injection is successful

### ISSUE THREAD

**Issue by EliTheCoder** [Smertig/among-us-replay-mod#4]
I'd like to see a feature where you can see if the library is injected with some text or a symbol in game. Just a suggestion

**Comment by Smertig** [comment]
Hi. Thanks for suggestion!

Just for now you can run injector from terminal (`cmd.exe`) to see output (success or fail). I've thought about more informative notifications like message box, but I accidentally forgot to do that.

Will be implemented in next update.

**Comment by r1bnc** [comment]
Please add 11.4s support.
