### ISSUE TITLE
Support for 12.5

### ISSUE THREAD

**Issue by WNnitro50** [Smertig/among-us-replay-mod#7]
_i just want a support for the latest version._

**Comment by r1bnc** [comment]
Update, we now have 12.9

**Comment by Smertig** [comment]
Checkout [v0.6.5](https://github.com/Smertig/among-us-replay-mod/releases/tag/v0.6.5) for **v2020.12.9s** game version support

**Comment by r1bnc** [comment]
Can you add steps on how to compile this? maybe in the readme

Do I need Visual Studio 2019 ( a huge download for me, im stuck with Vs2012)? (which are you using?) 
ps. I already installed conan and cmake on windows

**Comment by Smertig** [comment]
@gr01d unfortunately, to compile mod manually you need one of the latest VS version (mine is `Microsoft Visual Studio Community 2019 Version 16.7.5`). I don't know what is the _minimal_ required version. I use C++17 and some features from C++20 that are definitely missing in VS 2015 and earlier.

P.S. Please, open new issue if you have question or suggestion. Comments can easily get lost.
